// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2SLLgvzkX2ZpdIRz_Z6FvHByXu0OGvi8',
    appId: '1:676126346166:web:12c4cff6c0a6556cbe0f17',
    messagingSenderId: '676126346166',
    projectId: 'todo-firebase-628ce',
    authDomain: 'todo-firebase-628ce.firebaseapp.com',
    databaseURL: 'https://todo-firebase-628ce-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-628ce.appspot.com',
    measurementId: 'G-596W9LPS59',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqz1bCcbzk0CTYQBaB0P1KPkT_4yj-N8',
    appId: '1:676126346166:android:2317210653c2a268be0f17',
    messagingSenderId: '676126346166',
    projectId: 'todo-firebase-628ce',
    databaseURL: 'https://todo-firebase-628ce-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-628ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASyAEuvrKchny65vd5t_RKL9BkgSSTwwg',
    appId: '1:676126346166:ios:efb2f2e86322786abe0f17',
    messagingSenderId: '676126346166',
    projectId: 'todo-firebase-628ce',
    databaseURL: 'https://todo-firebase-628ce-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-628ce.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASyAEuvrKchny65vd5t_RKL9BkgSSTwwg',
    appId: '1:676126346166:ios:efb2f2e86322786abe0f17',
    messagingSenderId: '676126346166',
    projectId: 'todo-firebase-628ce',
    databaseURL: 'https://todo-firebase-628ce-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-628ce.appspot.com',
    iosBundleId: 'com.example.todoFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2SLLgvzkX2ZpdIRz_Z6FvHByXu0OGvi8',
    appId: '1:676126346166:web:c4433391b7bb7f3ebe0f17',
    messagingSenderId: '676126346166',
    projectId: 'todo-firebase-628ce',
    authDomain: 'todo-firebase-628ce.firebaseapp.com',
    databaseURL: 'https://todo-firebase-628ce-default-rtdb.firebaseio.com',
    storageBucket: 'todo-firebase-628ce.appspot.com',
    measurementId: 'G-WC3EPFPZ8Z',
  );
}
